import * as Fa from 'react-icons/fa';
import * as Hi from 'react-icons/hi';
import * as Io from 'react-icons/io5';
import type { IconType } from 'react-icons';

const iconMap: Record<string, IconType> = {
  FaBoxOpen: Fa.FaBoxOpen,
  FaIndustry: Fa.FaIndustry,
  FaPrint: Fa.FaPrint,
  FaTabletAlt: Fa.FaTabletAlt,
  FaTags: Fa.FaTags,
  FaPills: Fa.FaPills,
  FaCog: Fa.FaCog,
  FaUtensils: Fa.FaUtensils,
  FaFlask: Fa.FaFlask,
  FaSpa: Fa.FaSpa,
  FaShoppingBag: Fa.FaShoppingBag,
  FaTshirt: Fa.FaTshirt,
  FaChartLine: Fa.FaChartLine,
  FaCheckCircle: Fa.FaCheckCircle,
  FaShieldAlt: Fa.FaShieldAlt,
  FaTruck: Fa.FaTruck,
  FaStar: Fa.FaStar,
  FaDollarSign: Fa.FaDollarSign,
  FaLayerGroup: Fa.FaLayerGroup,
  FaHeadset: Fa.FaHeadset,
  FaArrowRight: Fa.FaArrowRight,
  FaArrowLeft: Fa.FaArrowLeft,
  FaChevronRight: Fa.FaChevronRight,
  FaExpand: Fa.FaExpand,
  FaPhone: Fa.FaPhone,
  FaEnvelope: Fa.FaEnvelope,
  FaMapMarkerAlt: Fa.FaMapMarkerAlt,
  FaWhatsapp: Fa.FaWhatsapp,
  FaPaperclip: Fa.FaPaperclip,
  FaTimes: Fa.FaTimes,
  FaBullseye: Fa.FaBullseye,
  FaEye: Fa.FaEye,
  FaAward: Fa.FaAward,
  FaHandshake: Fa.FaHandshake,
  FaFacebookF: Fa.FaFacebookF,
  FaInstagram: Fa.FaInstagram,
  FaLinkedinIn: Fa.FaLinkedinIn,
  FaYoutube: Fa.FaYoutube,
  FaChevronUp: Fa.FaChevronUp,
  FaSearch: Fa.FaSearch,
  FaQuoteLeft: Fa.FaQuoteLeft,
  FaCalendarAlt: Fa.FaCalendarAlt,
  FaFileAlt: Fa.FaFileAlt,
  FaRulerCombined: Fa.FaRulerCombined,
  FaPalette: Fa.FaPalette,
  FaCut: Fa.FaCut,
  FaHotjar: Fa.FaHotjar,
  FaLeaf: Fa.FaLeaf,
  FaWater: Fa.FaWater,
  FaSun: Fa.FaSun,
  FaTint: Fa.FaTint,
  FaTools: Fa.FaTools,
  FaCompress: Fa.FaCompress,
  FaGripLines: Fa.FaGripLines,
  FaCubes: Fa.FaCubes,
  FaClipboardCheck: Fa.FaClipboardCheck,
  FaShippingFast: Fa.FaShippingFast,
  FaCommentDots: Fa.FaCommentDots,
  FaRegFile: Fa.FaRegFile,
  FaRegLightbulb: Fa.FaRegLightbulb,
  FaRegCheckCircle: Fa.FaRegCheckCircle,
  HiMenu: Hi.HiMenu,
  HiX: Hi.HiX,
  HiSun: Hi.HiSun,
  HiMoon: Hi.HiMoon,
  IoArrowForward: Io.IoArrowForward,
  IoArrowBack: Io.IoArrowBack,
};

export function getIcon(name: string): IconType {
  return iconMap[name] || Fa.FaBoxOpen;
}
